version: 2

sources:
  - name: main
    schema: main
    tables:
      - name: semesters
      - name: instructors
      - name: courses
      - name: students
      - name: prerequisites
      - name: enrollments